import {
  Client,
  Service,
  Appointment,
  Transaction,
  BusinessConfig,
  User,
} from "../types";

export const sampleUser: User = {
  id: "1",
  email: "admin@agendafixa.com",
  name: "Administrador",
  role: "admin",
  avatar: undefined,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const sampleServices: Service[] = [
  {
    id: "1",
    name: "Corte Masculino",
    description: "Corte moderno e estiloso com acabamento profissional",
    price: 25,
    duration: 30,
    category: "Corte",
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Barba",
    description: "Aparar e modelar barba com produtos premium",
    price: 20,
    duration: 20,
    category: "Barba",
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Combo Corte + Barba",
    description: "Pacote completo com corte e barba",
    price: 40,
    duration: 45,
    category: "Combo",
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Tratamento Capilar",
    description: "Hidratação e tratamento para cabelos danificados",
    price: 35,
    duration: 60,
    category: "Tratamento",
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleClients: Client[] = [
  {
    id: "1",
    name: "João Silva",
    email: "joao@email.com",
    phone: "(11) 99999-1111",
    birthDate: "1990-05-15",
    address: "Rua das Flores, 123 - São Paulo/SP",
    notes: "Prefere cortes mais conservadores",
    totalAppointments: 12,
    totalSpent: 480,
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Pedro Santos",
    email: "pedro@email.com",
    phone: "(11) 99999-2222",
    birthDate: "1985-08-22",
    totalAppointments: 8,
    totalSpent: 320,
    createdAt: new Date("2024-02-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Carlos Oliveira",
    email: "carlos@email.com",
    phone: "(11) 99999-3333",
    birthDate: "1992-12-03",
    notes: "Alérgico a alguns produtos",
    totalAppointments: 15,
    totalSpent: 600,
    createdAt: new Date("2023-11-20").toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleAppointments: Appointment[] = [
  {
    id: "1",
    clientId: "1",
    serviceId: "3",
    date: new Date().toISOString().split("T")[0],
    time: "09:00",
    status: "confirmed",
    totalPrice: 40,
    notes: "Cliente solicitou corte mais baixo nas laterais",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    clientId: "2",
    serviceId: "1",
    date: new Date().toISOString().split("T")[0],
    time: "14:00",
    status: "pending",
    totalPrice: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    clientId: "3",
    serviceId: "2",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    time: "10:30",
    status: "confirmed",
    totalPrice: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Shampoo Premium",
    description: "Shampoo anticaspa para todos os tipos de cabelo",
    category: "Cuidados",
    quantity: 15,
    minQuantity: 5,
    price: 25,
    cost: 12,
    supplier: "Fornecedor ABC",
    barcode: "123456789",
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Pomada Modeladora",
    description: "Pomada para fixação e brilho",
    category: "Styling",
    quantity: 3,
    minQuantity: 5,
    price: 30,
    cost: 15,
    supplier: "Fornecedor XYZ",
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Óleo para Barba",
    description: "Óleo hidratante para barba",
    category: "Barba",
    quantity: 8,
    minQuantity: 3,
    price: 35,
    cost: 18,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleTransactions: Transaction[] = [
  {
    id: "1",
    type: "income",
    category: "Serviços",
    description: "Corte + Barba - João Silva",
    amount: 40,
    date: new Date().toISOString().split("T")[0],
    appointmentId: "1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    type: "expense",
    category: "Produtos",
    description: "Compra de produtos para estoque",
    amount: 150,
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    notes: "Reposição mensal de estoque",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    type: "expense",
    category: "Equipamentos",
    description: "Manutenção de equipamentos",
    amount: 80,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    notes: "Manutenção preventiva das máquinas",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleBusinessConfig: BusinessConfig = {
  id: "1",
  name: "Barbearia ModernCut",
  description: "A melhor barbearia da região",
  address: "Rua Principal, 456 - Centro, São Paulo/SP",
  phone: "(11) 3333-4444",
  email: "contato@moderncut.com.br",
  website: "www.moderncut.com.br",
  openingHours: {
    monday: { open: "09:00", close: "18:00", closed: false },
    tuesday: { open: "09:00", close: "18:00", closed: false },
    wednesday: { open: "09:00", close: "18:00", closed: false },
    thursday: { open: "09:00", close: "18:00", closed: false },
    friday: { open: "09:00", close: "19:00", closed: false },
    saturday: { open: "08:00", close: "17:00", closed: false },
    sunday: { open: "09:00", close: "15:00", closed: true },
  },
  timeSlotDuration: 30,
  advanceBookingDays: 30,
  cancellationHours: 24,
  theme: "light",
  notifications: {
    email: true,
    whatsapp: true,
    sms: false,
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
